SET SEARCH_PATH TO cooking_camel_schema;

BEGIN;

INSERT INTO "ingredient" 
VALUES
(DEFAULT, 'warm water'),
(DEFAULT, 'cheez Whiz'),
(DEFAULT, 'paraffin'),
(DEFAULT, 'Salad Supreme seasoning'),
(DEFAULT, 'oil of cinnamon'),
(DEFAULT, 'applesauce'),
(DEFAULT, 'baking potatoes'),
(DEFAULT, 'purple grapes'),
(DEFAULT, 'orange sliced candy'),
(DEFAULT, 'ground black pepper'),
(DEFAULT, 'containers'),
(DEFAULT, 'baby food'),
(DEFAULT, 'whipped cream'),
(DEFAULT, 'sweet onions'),
(DEFAULT, 'pickle juice'),
(DEFAULT, 'cleaned strawberries'),
(DEFAULT, 'sage'),
(DEFAULT, 'cranberry sauce'),
(DEFAULT, 'bean sprouts'),
(DEFAULT, 'Worcestershire sauce'),
(DEFAULT, 'fresh blackberries'),
(DEFAULT, 'oranges'),
(DEFAULT, 'alum'),
(DEFAULT, 'sweet relish'),
(DEFAULT, 'cream of mushroom soup'),
(DEFAULT, 'pistachio instant pudding'),
(DEFAULT, 'grated carrot'),
(DEFAULT, 'ginger root'),
(DEFAULT, 'cayenne pepper'),
(DEFAULT, 'orange gelatin'),
(DEFAULT, 'cherry pie filling'),
(DEFAULT, 'eggplant'),
(DEFAULT, 'Bisquick'),
(DEFAULT, 'apple jelly'),
(DEFAULT, 'granulated sugar'),
(DEFAULT, 'Parmesan'),
(DEFAULT, 'pineapple juice'),
(DEFAULT, 'bread crumbs'),
(DEFAULT, 'long'),
(DEFAULT, 'buttered bread crumbs'),
(DEFAULT, 'green bell pepper'),
(DEFAULT, 'fully cooked Canadian bacon'),
(DEFAULT, 'Duncan'),
(DEFAULT, 'frankfurters'),
(DEFAULT, 'celery'),
(DEFAULT, 'clove garlic'),
(DEFAULT, 'cinnamon'),
(DEFAULT, 'N'),
(DEFAULT, 'lemon flavor'),
(DEFAULT, 'Tea'),
(DEFAULT, 'cherry pie mix'),
(DEFAULT, 'condensed milk'),
(DEFAULT, 'shortening'),
(DEFAULT, 'onion'),
(DEFAULT, 'yellow beans'),
(DEFAULT, 'lime'),
(DEFAULT, 'lemon'),
(DEFAULT, 'ground chuck'),
(DEFAULT, 'yellow cake mix'),
(DEFAULT, 'greens'),
(DEFAULT, 'lima beans'),
(DEFAULT, 'baking soda'),
(DEFAULT, 'syrup'),
(DEFAULT, 'chicken'),
(DEFAULT, 'onion salt'),
(DEFAULT, 'chunky spaghetti sauce'),
(DEFAULT, 'sugar'),
(DEFAULT, 'vanilla flavor'),
(DEFAULT, 'oatmeal'),
(DEFAULT, 'herbs'),
(DEFAULT, 'fresh fruits'),
(DEFAULT, 'cooking oats'),
(DEFAULT, 'unsweetened applesauce'),
(DEFAULT, 'whole wheat flour'),
(DEFAULT, 'O'),
(DEFAULT, 'Tabasco sauce'),
(DEFAULT, 'fresh blueberries'),
(DEFAULT, 'green chili peppers'),
(DEFAULT, 'olives'),
(DEFAULT, 'pie shells'),
(DEFAULT, 'cherry juice'),
(DEFAULT, 'carrots'),
(DEFAULT, 'graham cracker crust'),
(DEFAULT, 'drops red pepper sauce'),
(DEFAULT, 'dark sweet pitted cherries'),
(DEFAULT, 'mandarin oranges'),
(DEFAULT, 'cayenne'),
(DEFAULT, 'grape jelly'),
(DEFAULT, 'bacon bits'),
(DEFAULT, 'ground allspice'),
(DEFAULT, 'shredded Monterey Jack cheese'),
(DEFAULT, 'buttermilk'),
(DEFAULT, 'fresh ground black pepper'),
(DEFAULT, 'Campbells cream'),
(DEFAULT, 'pepper'),
(DEFAULT, 'green baby'),
(DEFAULT, 'rosemary'),
(DEFAULT, 'whole cloves'),
(DEFAULT, 'instant pudding'),
(DEFAULT, 'sherry'),
(DEFAULT, 'sweet chocolate chips'),
(DEFAULT, 'cornflakes'),
(DEFAULT, 'bell pepper'),
(DEFAULT, 'kidney beans'),
(DEFAULT, 'Italian dressing'),
(DEFAULT, 'grated sharp'),
(DEFAULT, 'tomato paste'),
(DEFAULT, 'frozen green beans'),
(DEFAULT, 'almond'),
(DEFAULT, 'red wine vinegar'),
(DEFAULT, 'picante sauce'),
(DEFAULT, 'Triple Sec'),
(DEFAULT, 'brown rice'),
(DEFAULT, 'caraway seed'),
(DEFAULT, 'sweet sausage'),
(DEFAULT, 'cream of shrimp soup'),
(DEFAULT, 'nutmeg'),
(DEFAULT, 'green onion'),
(DEFAULT, 'shell'),
(DEFAULT, 'bell peppers'),
(DEFAULT, 'beans'),
(DEFAULT, 'sauerkraut'),
(DEFAULT, 'melted meat drippings'),
(DEFAULT, 'salad'),
(DEFAULT, 'celery salt'),
(DEFAULT, 'olive'),
(DEFAULT, 'lemon jello'),
(DEFAULT, 'cucumbers'),
(DEFAULT, 'egg'),
(DEFAULT, 'white syrup'),
(DEFAULT, 'beef for stew'),
(DEFAULT, 'white cake mix'),
(DEFAULT, 'broccoli florets'),
(DEFAULT, 'white Karo syrup'),
(DEFAULT, 'pork roast'),
(DEFAULT, 'butter beans'),
(DEFAULT, 'salsa'),
(DEFAULT, 'okra'),
(DEFAULT, 'sweet potatoes'),
(DEFAULT, 'pinto beans'),
(DEFAULT, 'breadcrumbs'),
(DEFAULT, 'chocolate wafers'),
(DEFAULT, 'Spanish rice'),
(DEFAULT, 'currant jelly'),
(DEFAULT, 'stuffing mix'),
(DEFAULT, 'cloves'),
(DEFAULT, 'red Spanish'),
(DEFAULT, 'caramel topping'),
(DEFAULT, 'light Karo syrup'),
(DEFAULT, 'Muenster'),
(DEFAULT, 'vegetables'),
(DEFAULT, 'allspice'),
(DEFAULT, 'lite'),
(DEFAULT, 'white grape juice'),
(DEFAULT, 'mushroom soup'),
(DEFAULT, 'apple cider vinegar'),
(DEFAULT, 'Manwich'),
(DEFAULT, 'crescent rolls'),
(DEFAULT, 'corn'),
(DEFAULT, 'crackers'),
(DEFAULT, 'walnuts'),
(DEFAULT, 'apple'),
(DEFAULT, 'coconut flavoring'),
(DEFAULT, 'your choice'),
(DEFAULT, 'romaine lettuce'),
(DEFAULT, 'apricot nectar'),
(DEFAULT, 'Milk'),
(DEFAULT, 'condensed cream'),
(DEFAULT, 'crabmeat'),
(DEFAULT, 'tamari sauce'),
(DEFAULT, 'egg yolk'),
(DEFAULT, 'rum flavoring'),
(DEFAULT, 'beef'),
(DEFAULT, 'vegetable oil'),
(DEFAULT, 'chicken breasts'),
(DEFAULT, 'peach slices'),
(DEFAULT, 'rye bread'),
(DEFAULT, 'Swans'),
(DEFAULT, 'crisp fried bacon'),
(DEFAULT, 'fresh parsley'),
(DEFAULT, 'thin'),
(DEFAULT, 'cake'),
(DEFAULT, 'sesame seed'),
(DEFAULT, 'vegetable cooking spray'),
(DEFAULT, 'peaches'),
(DEFAULT, 'butternut flavoring'),
(DEFAULT, 'American cheese'),
(DEFAULT, 'corn bread'),
(DEFAULT, 'white sugar'),
(DEFAULT, 'ground ginger'),
(DEFAULT, 'cranberries'),
(DEFAULT, 'egg yolks'),
(DEFAULT, 'Fritos'),
(DEFAULT, 'chicken bouillon'),
(DEFAULT, 'nuts'),
(DEFAULT, 'cider vinegar'),
(DEFAULT, 'onion soup'),
(DEFAULT, 'coarse black pepper'),
(DEFAULT, 'slivered almonds'),
(DEFAULT, 'steak seasoning'),
(DEFAULT, 'crab'),
(DEFAULT, 'red apples'),
(DEFAULT, 'artichokes'),
(DEFAULT, 'guacamole dip'),
(DEFAULT, 'vanilla pudding'),
(DEFAULT, 'vegetable soup mix'),
(DEFAULT, 'cake yeast'),
(DEFAULT, 'cold water'),
(DEFAULT, 'safflower oil'),
(DEFAULT, 'water chestnuts'),
(DEFAULT, 'English peas'),
(DEFAULT, 'extra lean ground beef'),
(DEFAULT, 'mushrooms'),
(DEFAULT, 'sharp cheese'),
(DEFAULT, 'pimento'),
(DEFAULT, 'ground cloves'),
(DEFAULT, 'Crisco oil'),
(DEFAULT, 'nonfat plain yogurt'),
(DEFAULT, 'frozen raspberry'),
(DEFAULT, 'Tomato'),
(DEFAULT, 'chocolate syrup'),
(DEFAULT, 'pumpkin pie spice'),
(DEFAULT, 'cream'),
(DEFAULT, 'whole kernel golden corn'),
(DEFAULT, 'yellow cake'),
(DEFAULT, 'butterscotch pudding'),
(DEFAULT, 'chicken broth'),
(DEFAULT, 'frozen spinach'),
(DEFAULT, 'oregano'),
(DEFAULT, 'macaroni'),
(DEFAULT, 'pineapple'),
(DEFAULT, 'pastry shell'),
(DEFAULT, 'cottage cheese'),
(DEFAULT, 'nonstick vegetable cooking spray'),
(DEFAULT, 'hot pepper'),
(DEFAULT, 'vanilla ice cream'),
(DEFAULT, 'yellow lima beans'),
(DEFAULT, 'caramel sauce'),
(DEFAULT, 'flour'),
(DEFAULT, 'cheese slices'),
(DEFAULT, 'Velveeta'),
(DEFAULT, 'salmon'),
(DEFAULT, 'butternut flavor'),
(DEFAULT, 'yellow food coloring'),
(DEFAULT, 'orange flavoring'),
(DEFAULT, 'Angel'),
(DEFAULT, 'deluxe white cake mix'),
(DEFAULT, 'apples'),
(DEFAULT, 'Parmesan cheese'),
(DEFAULT, 'cold milk'),
(DEFAULT, 'ginger'),
(DEFAULT, 'Ricotta cheese'),
(DEFAULT, 'cheese'),
(DEFAULT, 'taco sauce'),
(DEFAULT, 'marshmallows'),
(DEFAULT, 'lemons'),
(DEFAULT, 'caraway'),
(DEFAULT, 'pecan pieces'),
(DEFAULT, 'head lettuce'),
(DEFAULT, 'hash browns'),
(DEFAULT, 'cashews'),
(DEFAULT, 'liters ginger ale'),
(DEFAULT, 'egg white'),
(DEFAULT, 'light cream'),
(DEFAULT, 'nonfat mayonnaise'),
(DEFAULT, 'ground raisins'),
(DEFAULT, 'lean hamburger'),
(DEFAULT, 'green chili'),
(DEFAULT, 'yellow hominy'),
(DEFAULT, 'beef brisket'),
(DEFAULT, 'tomato sauce'),
(DEFAULT, 'cream of celery soup'),
(DEFAULT, 'tart cherries'),
(DEFAULT, 'flavored gelatin'),
(DEFAULT, 'shells'),
(DEFAULT, 'lard'),
(DEFAULT, 'sauce'),
(DEFAULT, 'salt'),
(DEFAULT, 'light brown sugar'),
(DEFAULT, 'solid pack pumpkin'),
(DEFAULT, 'soy sauce'),
(DEFAULT, 'vegetable shortening'),
(DEFAULT, 'chicken soup'),
(DEFAULT, 'cayenne red pepper'),
(DEFAULT, 'Bananas'),
(DEFAULT, 'tortillas'),
(DEFAULT, 'nonfat yogurt'),
(DEFAULT, 'unsweetened cocoa'),
(DEFAULT, 'rolls'),
(DEFAULT, 'maraschino cherries'),
(DEFAULT, 'jars Junior baby food'),
(DEFAULT, 'pastry'),
(DEFAULT, 'brown Sugar'),
(DEFAULT, 'egg noodles'),
(DEFAULT, 'water'),
(DEFAULT, 'navy beans'),
(DEFAULT, 'tortilla chips'),
(DEFAULT, 'Chinese noodles'),
(DEFAULT, 'garlic'),
(DEFAULT, 'frozen corn'),
(DEFAULT, 'jalapeno pepper'),
(DEFAULT, 'frozen artichoke'),
(DEFAULT, 'Campbells chunky'),
(DEFAULT, 'Swiss'),
(DEFAULT, 'bread'),
(DEFAULT, 'sausage'),
(DEFAULT, 'bacon grease'),
(DEFAULT, 'salad oil'),
(DEFAULT, 'mandarin juice'),
(DEFAULT, 'chocolate fudge cake'),
(DEFAULT, 'cracker crumbs'),
(DEFAULT, 'anchovies'),
(DEFAULT, 'apricot preserves'),
(DEFAULT, 'pie crust'),
(DEFAULT, 'cabbage'),
(DEFAULT, 'flavor gelatin'),
(DEFAULT, 'graham crackers'),
(DEFAULT, 'Mozzarella cheese'),
(DEFAULT, 'sweet peas'),
(DEFAULT, 'hot water'),
(DEFAULT, 'cooking apples'),
(DEFAULT, 'unsalted soda crackers'),
(DEFAULT, 'lean ground beef'),
(DEFAULT, 'mix'),
(DEFAULT, 'hen'),
(DEFAULT, 'flounder'),
(DEFAULT, 'ground pork'),
(DEFAULT, 'pimentos'),
(DEFAULT, 'Velveeta cheese'),
(DEFAULT, 'corn tortillas'),
(DEFAULT, 'apple vinegar'),
(DEFAULT, 'frozen strawberries'),
(DEFAULT, 'fresh mushrooms'),
(DEFAULT, 'Philadelphia cream cheese'),
(DEFAULT, 'green sweet peppers'),
(DEFAULT, 'Romano cheese'),
(DEFAULT, 'frozen broccoli'),
(DEFAULT, 'grated cheese'),
(DEFAULT, '+'),
(DEFAULT, 'almond flavoring'),
(DEFAULT, 'bananas'),
(DEFAULT, 'peppers'),
(DEFAULT, 'Rice Krispies'),
(DEFAULT, 'ground beef'),
(DEFAULT, 'coconut'),
(DEFAULT, 'turmeric'),
(DEFAULT, 'tuna'),
(DEFAULT, 'brown sugar'),
(DEFAULT, 'carrot chunks'),
(DEFAULT, 'beef stock'),
(DEFAULT, 'white cake'),
(DEFAULT, 'ground nuts'),
(DEFAULT, 'black cherry'),
(DEFAULT, 'unsweetened chocolate'),
(DEFAULT, 'grapes'),
(DEFAULT, 'cake flour'),
(DEFAULT, 'ham bone'),
(DEFAULT, 'snow peas'),
(DEFAULT, 'melted Crisco'),
(DEFAULT, 'vanilla instant pudding mix'),
(DEFAULT, 'mixed vegetables'),
(DEFAULT, 'onion powder'),
(DEFAULT, 'cornflake crumbs'),
(DEFAULT, 'persimmon pulp'),
(DEFAULT, 'peanuts'),
(DEFAULT, 'zucchini'),
(DEFAULT, 'Boyardee'),
(DEFAULT, 'Crisco'),
(DEFAULT, 'parmesan cheese'),
(DEFAULT, 'tomato soup'),
(DEFAULT, 'Italian salad dressing'),
(DEFAULT, 'vanilla extract'),
(DEFAULT, 'parsley flakes'),
(DEFAULT, 'cranberry juice'),
(DEFAULT, 'ham'),
(DEFAULT, 'curry powder'),
(DEFAULT, 'cornmeal'),
(DEFAULT, 'Frango'),
(DEFAULT, 'butter'),
(DEFAULT, 'Pet milk'),
(DEFAULT, 'rhubarb'),
(DEFAULT, 'club soda'),
(DEFAULT, 'dates'),
(DEFAULT, 'Italian seasoning'),
(DEFAULT, 'tamales'),
(DEFAULT, 'ketchup'),
(DEFAULT, 'light corn syrup'),
(DEFAULT, 'pear halves'),
(DEFAULT, 'carrot'),
(DEFAULT, 'dinner rolls'),
(DEFAULT, 'pineapple tidbits'),
(DEFAULT, 'oil'),
(DEFAULT, 'almonds'),
(DEFAULT, 'basil'),
(DEFAULT, 'milk'),
(DEFAULT, 'nut meats'),
(DEFAULT, 'confectioners sugar'),
(DEFAULT, 'Accent'),
(DEFAULT, 'frozen peas'),
(DEFAULT, 'candied cherries'),
(DEFAULT, 'Salt'),
(DEFAULT, 'corn meal'),
(DEFAULT, 'grenadine syrup'),
(DEFAULT, 'ground turkey'),
(DEFAULT, 'white corn syrup'),
(DEFAULT, 'green chili salsa sauce'),
(DEFAULT, 'blueberries'),
(DEFAULT, 'dill'),
(DEFAULT, 'chili powder'),
(DEFAULT, 'whole kernel corn'),
(DEFAULT, 'salt pork'),
(DEFAULT, 'lemon instant pudding'),
(DEFAULT, 'oleo'),
(DEFAULT, 'mushroom'),
(DEFAULT, 'apple pie spice'),
(DEFAULT, 'Cayenne Pepper'),
(DEFAULT, 'nonfat buttermilk'),
(DEFAULT, 'corn tortilla'),
(DEFAULT, 'tomato juice'),
(DEFAULT, 'floured blueberries'),
(DEFAULT, 'Parsley'),
(DEFAULT, 'pecan'),
(DEFAULT, 'corn flakes'),
(DEFAULT, 'white'),
(DEFAULT, 'chocolate'),
(DEFAULT, 'green chillies'),
(DEFAULT, 'noodle soup'),
(DEFAULT, 'black walnuts'),
(DEFAULT, 'croutons'),
(DEFAULT, 'wine vinegar'),
(DEFAULT, 'cornbread mix'),
(DEFAULT, 'chicken gravy'),
(DEFAULT, 'crust'),
(DEFAULT, 'powdered sugar'),
(DEFAULT, 'strawberry'),
(DEFAULT, 'celery powder'),
(DEFAULT, 'unflavored gelatine'),
(DEFAULT, 'wild rice'),
(DEFAULT, 'pork sausage'),
(DEFAULT, 'peach juice from'),
(DEFAULT, 'crushed ice'),
(DEFAULT, 'cherries'),
(DEFAULT, 'almond extract'),
(DEFAULT, 'paprika'),
(DEFAULT, 'soda'),
(DEFAULT, 'salsa sauce'),
(DEFAULT, 'pimiento'),
(DEFAULT, 'graham cracker crumbs'),
(DEFAULT, 'cauliflower'),
(DEFAULT, 'stalks celery'),
(DEFAULT, 'fresh tomato'),
(DEFAULT, 'Vidalia onion'),
(DEFAULT, 'Ground Beef'),
(DEFAULT, 'ham bouillon'),
(DEFAULT, 'frozen lemonade concentrate'),
(DEFAULT, 'orange juice concentrate'),
(DEFAULT, 'tarragon'),
(DEFAULT, 'chuck roast'),
(DEFAULT, 'flax seed'),
(DEFAULT, 'marjoram'),
(DEFAULT, 'graham cracker crusts'),
(DEFAULT, 'chickpeas'),
(DEFAULT, 'Salad Supreme'),
(DEFAULT, 'shredded Monterey Jack'),
(DEFAULT, 'pink salmon'),
(DEFAULT, 'sour milk'),
(DEFAULT, 'mango'),
(DEFAULT, 'bay leaves'),
(DEFAULT, 'commerical sour cream'),
(DEFAULT, 'cream of tartar'),
(DEFAULT, 'consomme'),
(DEFAULT, 'boiling water'),
(DEFAULT, 'white vinegar'),
(DEFAULT, 'lemon yogurt'),
(DEFAULT, 'cool whip'),
(DEFAULT, 'cherry jello'),
(DEFAULT, 'barbecue sauce'),
(DEFAULT, 'chicken stock'),
(DEFAULT, 'tapioca'),
(DEFAULT, 'steak'),
(DEFAULT, 'Borden milk'),
(DEFAULT, 'skinless'),
(DEFAULT, 'chili sauce'),
(DEFAULT, 'beef bouillon'),
(DEFAULT, 'brandy'),
(DEFAULT, 'lasagne noodles'),
(DEFAULT, 'pie filling'),
(DEFAULT, 'mushroom stems'),
(DEFAULT, 'vanilla'),
(DEFAULT, 'dill weed'),
(DEFAULT, 'oysters'),
(DEFAULT, 'fresh cranberries'),
(DEFAULT, 'spaghetti'),
(DEFAULT, 'white wine'),
(DEFAULT, 'lime gelatin'),
(DEFAULT, 'sweet milk'),
(DEFAULT, 'pickling spice'),
(DEFAULT, 'ground meat'),
(DEFAULT, 'shredded cheese'),
(DEFAULT, 'arborio'),
(DEFAULT, 'sweet basil'),
(DEFAULT, 'yellow apples'),
(DEFAULT, 'Ramen noodles'),
(DEFAULT, 'mayo'),
(DEFAULT, 'margarine'),
(DEFAULT, 'red wine'),
(DEFAULT, 'summer squash'),
(DEFAULT, 'roll'),
(DEFAULT, 'honey'),
(DEFAULT, 'banana'),
(DEFAULT, 'scallions'),
(DEFAULT, 'Miracle'),
(DEFAULT, 'vanilla instant pudding'),
(DEFAULT, 'noodles'),
(DEFAULT, 'baking chocolate'),
(DEFAULT, 'frozen lemonade'),
(DEFAULT, 'broccoli'),
(DEFAULT, 'yeast'),
(DEFAULT, 'Hormel chili'),
(DEFAULT, 'garlic salt'),
(DEFAULT, 'sour cream'),
(DEFAULT, 'corn syrup'),
(DEFAULT, 'egg dumpling noodles'),
(DEFAULT, 'buttered toast'),
(DEFAULT, 'marshmallow cream'),
(DEFAULT, 'garlic powder'),
(DEFAULT, 'green chilies'),
(DEFAULT, 'ground red pepper'),
(DEFAULT, 'chocolate cake'),
(DEFAULT, 'cooking oil'),
(DEFAULT, 'alfalfa honey'),
(DEFAULT, 'ground lean beef'),
(DEFAULT, 'crunchy peanut butter'),
(DEFAULT, 'cocoa'),
(DEFAULT, 'fresh dill'),
(DEFAULT, 'lemon pepper'),
(DEFAULT, 'Dream Whip'),
(DEFAULT, 'rice'),
(DEFAULT, 'pistachio pie filling'),
(DEFAULT, 'packets instant chicken broth'),
(DEFAULT, 'strawberry jello'),
(DEFAULT, 'beef consomme'),
(DEFAULT, 'hamburger'),
(DEFAULT, 'lemon extract'),
(DEFAULT, 'cake mix'),
(DEFAULT, 'chunk white chicken'),
(DEFAULT, 'pork'),
(DEFAULT, 'Butter'),
(DEFAULT, 'fresh strawberries'),
(DEFAULT, 'dry mustard'),
(DEFAULT, 'pepperoni'),
(DEFAULT, 'No'),
(DEFAULT, 'watermelon rind'),
(DEFAULT, 'Chicken'),
(DEFAULT, 'green beans'),
(DEFAULT, 'chop suey vegetables'),
(DEFAULT, 'egg whites'),
(DEFAULT, 'ground nutmeg'),
(DEFAULT, 'faux crabmeat'),
(DEFAULT, 'Swiss cheese'),
(DEFAULT, 'broccoli flowerets'),
(DEFAULT, 'hot bacon'),
(DEFAULT, 'maraschino cherry'),
(DEFAULT, 'broccoli heads'),
(DEFAULT, 'taco seasoning'),
(DEFAULT, 'onion flakes'),
(DEFAULT, 'biscuit mix'),
(DEFAULT, 'frozen limas'),
(DEFAULT, 'heavy cream'),
(DEFAULT, 'frozen mixed vegetables'),
(DEFAULT, 'whipping cream'),
(DEFAULT, 'taco'),
(DEFAULT, 'parsley'),
(DEFAULT, 'unflavored gelatin'),
(DEFAULT, 'spaghetti sauce'),
(DEFAULT, 'ground white pepper'),
(DEFAULT, 'candied fruit'),
(DEFAULT, 'chocolate cake mix'),
(DEFAULT, 'moist coconut'),
(DEFAULT, 'Tater'),
(DEFAULT, 'strawberries'),
(DEFAULT, 'fruit cocktail'),
(DEFAULT, 'vanilla wafers'),
(DEFAULT, 'Italian tomatoes'),
(DEFAULT, 'red Delicious apple'),
(DEFAULT, 'oats'),
(DEFAULT, 'catsup'),
(DEFAULT, 'peas'),
(DEFAULT, 'green onions'),
(DEFAULT, 'vermicelli'),
(DEFAULT, 'celery stalks'),
(DEFAULT, 'cornstarch'),
(DEFAULT, 'instant tea'),
(DEFAULT, 'orange jello'),
(DEFAULT, 'baking powder'),
(DEFAULT, 'chicken cutlets'),
(DEFAULT, 'bacon fat'),
(DEFAULT, 'bay leaf'),
(DEFAULT, 'mustard'),
(DEFAULT, 'thin green onion strips'),
(DEFAULT, 'red sweet peppers'),
(DEFAULT, 'bourbon'),
(DEFAULT, 'frozen raspberries'),
(DEFAULT, 'clump'),
(DEFAULT, 'molasses'),
(DEFAULT, 'bacon drippings'),
(DEFAULT, 'packets sugar substitute'),
(DEFAULT, 'white batter'),
(DEFAULT, 'purple onion'),
(DEFAULT, 'potato'),
(DEFAULT, 'horseradish'),
(DEFAULT, 'green pepper'),
(DEFAULT, 'white onion'),
(DEFAULT, 'meal'),
(DEFAULT, 'flaked coconut'),
(DEFAULT, 'corn flake crumbs'),
(DEFAULT, 'red vinegar'),
(DEFAULT, 'stew meat'),
(DEFAULT, 'nonstick cooking spray'),
(DEFAULT, 'tomato'),
(DEFAULT, 'Stove Top stuffing'),
(DEFAULT, 'apricot jello'),
(DEFAULT, 'potatoes OBrien'),
(DEFAULT, 'orange juice'),
(DEFAULT, 'fruit yogurt'),
(DEFAULT, 'onions'),
(DEFAULT, 'Eggs'),
(DEFAULT, 'pork tenderloin'),
(DEFAULT, 'grated ginger'),
(DEFAULT, 'peanut butter'),
(DEFAULT, 'graham cracker crumb crust'),
(DEFAULT, 'squash'),
(DEFAULT, 'Twinkies'),
(DEFAULT, 'black pepper'),
(DEFAULT, 'black coffee'),
(DEFAULT, 'pecans'),
(DEFAULT, 'sunflower seeds'),
(DEFAULT, 'lemon juice'),
(DEFAULT, 'shredded lettuce'),
(DEFAULT, 'pickles'),
(DEFAULT, 'raisins'),
(DEFAULT, 'cheddar cheese'),
(DEFAULT, 'hamburg'),
(DEFAULT, 'orange'),
(DEFAULT, 'beer'),
(DEFAULT, 'red'),
(DEFAULT, 'tomatoes'),
(DEFAULT, 'green peppers'),
(DEFAULT, 'ginger ale'),
(DEFAULT, 'onion soup mix'),
(DEFAULT, 'clams'),
(DEFAULT, 'peppermint candy'),
(DEFAULT, 'red cabbage'),
(DEFAULT, 'instant rice'),
(DEFAULT, 'pie shell'),
(DEFAULT, 'regular'),
(DEFAULT, 'salad dressing'),
(DEFAULT, 'poultry seasoning'),
(DEFAULT, 'Wesson oil'),
(DEFAULT, 'new potatoes'),
(DEFAULT, 'liquid smoke'),
(DEFAULT, 'potatoes'),
(DEFAULT, 'thyme'),
(DEFAULT, 'White Lily'),
(DEFAULT, 'chocolate pudding'),
(DEFAULT, 'chocolate chips'),
(DEFAULT, 'ground cumin'),
(DEFAULT, 'brisket'),
(DEFAULT, 'cream cheese'),
(DEFAULT, 'warm beer'),
(DEFAULT, 'milk chocolate'),
(DEFAULT, 'corned beef'),
(DEFAULT, 'fresh broccoli'),
(DEFAULT, 'mayonnaise'),
(DEFAULT, 'instant vanilla pudding'),
(DEFAULT, 'beef hash'),
(DEFAULT, 'cream of chicken soup'),
(DEFAULT, 'vanilla flavoring'),
(DEFAULT, 'lime sherbet'),
(DEFAULT, 'Country'),
(DEFAULT, 'white grapes'),
(DEFAULT, 'apple juice'),
(DEFAULT, 'olive oil'),
(DEFAULT, 'pumpkin'),
(DEFAULT, 'chives'),
(DEFAULT, 'croquette sauce'),
(DEFAULT, 'Cheddar cheese'),
(DEFAULT, 'unsalted butter'),
(DEFAULT, 'white Minute rice'),
(DEFAULT, 'spinach'),
(DEFAULT, 'ground cinnamon'),
(DEFAULT, 'green bell peppers'),
(DEFAULT, 'raw strawberries'),
(DEFAULT, 'bacon'),
(DEFAULT, 'oyster liquid'),
(DEFAULT, 'ready'),
(DEFAULT, 'chocolate fudge pudding'),
(DEFAULT, 'cereal'),
(DEFAULT, 'vinegar'),
(DEFAULT, 'eggs'),
(DEFAULT, 'green peas'),
(DEFAULT, 'bite size shredded rice biscuits');

COMMIT;